# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6  # Ensure this matches the version you're using
  hooks:
    - id: ruff
      args:
        - "--select"
        - "E,F,W,A,PLC,PLE,PLW,I"
        - "--fix"  # Optional, to auto-fix issues where possible
        - "--line-length"
        - "120"  # Set the line length to 120
    - id: ruff-format
      args:
        - "--line-length"
        - "120"  # Ensure the formatter also uses the same line length