name: Pre-commit Checks

on:
  pull_request:
    branches:
      - master # Replace with your default branch if different
  push:
    branches:
      - master # Optional, to run checks on pushes to main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Match your project's Python version

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit checks
        run: |
          pre-commit install
          pre-commit run --all-files
