name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  pre-publish:
    name: Prepare to Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev --upgrade

      - name: Run smoke tests
        run: uv run wled2graph --help

      - name: Build the package
        run: uv build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist
            build

  publish:
    name: Publish to PyPI
    needs: pre-publish
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Install uv
        uses: astral-sh/setup-uv@v5    

      - name: Publish to PyPI
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
