name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Trigger on tags like v1.0.0, v2.1.0, etc.

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install UV
        run: |
          pip install uv

      - name: Install dependencies
        run: uv install

      - name: Build the package
        run: uv build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
